spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      continue-on-error: true

app:
  events:
    dispatcher:
      enabled: true

logging:
  level:
    app.partsvibe.infra.events: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
